### ISSUE TITLE
[1.16.5] The ranks.json file is buggy...

### ISSUE THREAD

**Issue by Cixon** [FTBTeam/FTB-Ranks#13]
**Context:** I was trying to get my long term users of my server to take advantage of the 50 extra chunk claims
(total of 100) with the Legend role. Unfortunately they were still capped at 50. Which is the standard for new players in the server.

No matter how much I try to give the users with the Legend role a total of 100 max claims, rather that'd be leave the server and join back to refresh the client or even restart the server, nothing works.

What DOES work is the Council role for some reason which also takes advantage of the 100 max claims but this is a role I want to give **EXCLUSIVELY** to moderators/close friends.

### config setup:
[ranks.txt](https://github.com/FTBTeam/FTB-Ranks/files/5909578/ranks.txt)

Please let me know what I did wrong or if this is a bug! Thank you.

**Comment by Cixon** [comment]
and no, the ftbchunks mod config .toml is not capped at 50, it's at 100.

**Comment by Cixon** [comment]
**UPDATE:** So I figured out that there's just a reallly reallly long delay for users to receive their benefits once their ranks are updated.

This should be fixed.

**Comment by Column01** [comment]
> **UPDATE:** So I figured out that there's just a reallly reallly long delay for users to receive their benefits once their ranks are updated.
> 
> This should be fixed.

I looked at the code and if you force a save using `/save-all` it will automatically update the ranks for all users. It sadly only applies the ranks when the world saves
