### ISSUE TITLE
Wiki. 

### ISSUE THREAD

**Issue by berni1212** [FTBTeam/FTB-Ranks#16]
Fehler: Verbindung fehlgeschlagen

Firefox kann keine Verbindung zu dem Server unter faq.ftb.world aufbauen.

the wiki is offline. 
https://faq.ftb.world/books/ftb-utilities

How should we read the Docs if there aren't any?

**Comment by Quetzi** [comment]
Documentation has now moved to https://help.ftb.team/help/en-gb/7
