### ISSUE TITLE
How does the "and" condition work?

### ISSUE THREAD

**Issue by Dashinator** [FTBTeam/FTB-Ranks#24]
**Mod & Pack version**
FTB Ranks version: ftb-ranks-1605.1.4-build.5-forge.jar

I am trying to implement the "and" condition. But I can't find any documentation that includes it.
The rank I am trying to make is this. And from what I gather from the code, this should work.

member: {
		name: "Member"
		power: 4
		ftbranks.name_format: "[Member]{name}:"
		condition: {
			type: "and"
			conditions: {
				condition: {
					type: "rank_added"
					rank: beginner
				}
				condition: {
					type: "playtime"
					time: 10
					time_unit: "hours"
				}
			}
		}
	}

**Comment by MaxNeedsSnacks** [comment]
If I had to guess, the structure would more be something like this

```json5
{
    "member" : {
        "condition" : {
            "conditions" : [
                {
                    "rank" : "beginner",
                    "type" : "rank_added"
                },
                {
                    "time" : 10,
                    "time_unit" : "hours",
                    "type" : "playtime"
                }
            ],
            "type" : "and"
        },
        "ftbranks" : {
            "name_format" : "[Member]{name}:"
        },
        "name" : "Member",
        "power" : 4
    }
}
```

since duplicate keys in a map usually get erased (i.e. the two "condition" ones you have there would get merged into one)

**Comment by Dashinator** [comment]
Oh, you are amazing... I never thought about the [ ]. It doesnt need all the comma line ends. But it does work now. Thank you
