### ISSUE TITLE
Add rank for fake player

### ISSUE THREAD

**Issue by LatvianModder** [FTBTeam/FTB-Ranks#4]
https://github.com/FTBTeam/FTB-Utilities/issues/931

**Comment by MaxNeedsSnacks** [comment]
Implemented through https://github.com/FTBTeam/FTB-Ranks/blob/main/common/src/main/java/dev/ftb/mods/ftbranks/impl/condition/FakePlayerCondition.java, as pointed out by Jarva on Discord
